# pyproject.toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "casablanca-api"
version = "0.1.6"
description = "A client for the ATV Model API."
requires-python = ">=3.10"
dependencies = [
  "requests",
]
